chore: working changes

diff --git a/templates/frontend/deployment.yaml b/templates/frontend/deployment.yaml
--- a/templates/frontend/deployment.yaml
+++ b/templates/frontend/deployment.yaml
@@ -40,7 +40,6 @@ spec:
       {{- range .Values.imageCredentials }}
       - name: {{ .name }}
       {{- end }}
-      
       securityContext:
         {{- toYaml .Values.frontend.deployment.podSecurityContext | nindent 8 }}
       serviceAccountName: {{ include "frontend.serviceAccountName" . }}
@@ -68,23 +67,20 @@ spec:
             {{- with .Values.frontend.deployment.extraEnv }}
               {{- toYaml . | nindent 12 }}
             {{- end }}
-            # {{- if .Values.ingress.subdomain }}
-            # - name: VITE_SUBDOMAIN
-            #   value: {{ .Values.ingress.subdomain }}
-            # {{- end }}
             {{- with .Values.commonEnv }}
               {{ toYaml . | nindent 12 }}
             {{- end }}
-        #   envFrom:
-        #     - configMapRef:
-        #         name: {{ include "portkey.fullname" . }}-config
           image: "{{ .Values.images.frontendImage.repository }}:{{ .Values.images.frontendImage.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.images.frontendImage.pullPolicy }}
           command: ["/bin/sh", "-c"]
           args:
             - |
-              cp /config/nginx.conf /etc/nginx/conf.d/default.conf &&
-              cp /config/.env /usr/share/nginx/html/.env &&
+              echo "Starting copy operations..."
+              ls -l /config
+              cp /config/nginx.conf /etc/nginx/conf.d/default.conf && echo "nginx.conf copied" || echo "Failed to copy nginx.conf"
+              cp /config/config.js /usr/share/nginx/html/config.js && echo "config.js copied" || echo "Failed to copy config.js"
+              echo "Copy operations completed"
+              echo "Starting Nginx..."
               exec nginx -g 'daemon off;'
           ports:
             - name: frontend
@@ -110,12 +106,10 @@ spec:
             {{- with .Values.frontend.deployment.volumeMounts }}
               {{- toYaml . | nindent 12 }}
             {{- end }}
-            - name: config-volume
-              mountPath: /config
-            - name: nginx-config
-              mountPath: /etc/nginx/conf.d
             - name: app-config
-              mountPath: /usr/share/nginx/html
+              mountPath: /config
+            # - name: config-volume
+            #   mountPath: /config
           {{- with .Values.frontend.deployment.extraContainerConfig }}
             {{- toYaml . | nindent 10 }}
           {{- end }}
@@ -135,10 +129,11 @@ spec:
         {{- toYaml . | nindent 8 }}
       {{- end }}
       volumes:
-        - name: nginx-config
-          emptyDir: {}
         - name: app-config
-          emptyDir: {}
-        - name: config-volume
           configMap:
             name: {{ include "portkey.fullname" . }}-{{ .Values.frontend.name }}
+            # items:
+            #   - key: nginx.conf
+            #     path: nginx.conf
+            #   - key: config.js
+            #     path: config.js
